name: Lin Go Code

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.1'
      # - uses: golangci/golangci-lint-action@master
      #   with:
      #     # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
      #     version: v1.27
      #     github-token: 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
      
      - name: Lint
        run: | 
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
          
          golangci-lint run