name: Lin Go Code

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.1'
