name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Imaage
      run:  | 
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        echo ${{ secrets.DOCKER_USERNAME }} | sed 's/ ./&'
        echo ${{ secrets.DOCKER_PASSWORD }} | sed 's/ ./&'
        
    
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: naveeharn/golang-github-action
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
